//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRUSHSERVICE.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRUSHSERVICE_db_Entities : DbContext
    {
        public static GRUSHSERVICE_db_Entities _context;//приватное статичное поле контекст
        public GRUSHSERVICE_db_Entities()
            : base("name=GRUSHSERVICE_db_Entities")
        {
        }
        public static GRUSHSERVICE_db_Entities GetContext()
        {
            if (_context == null)
                _context = new GRUSHSERVICE_db_Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Sevices> Sevices { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
