//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRUSHSERVICE.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int id { get; set; }
        public Nullable<int> clients { get; set; }
        public Nullable<int> services { get; set; }
        public string documents { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
    
        public virtual Clients Clients1 { get; set; }
        public virtual Products Products { get; set; }
        public virtual Sevices Sevices { get; set; }
    }
}
